controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

nelmio_api_doc:
    controller: nelmio_api_doc.controller.swagger_ui
    path: /api/doc

fos_user:
    resource: '@FOSUserBundle/Resources/config/routing/all.xml'
    type: xml